version: '3'
services:
  mongo:
    image: 'mongo:4.4'
  postgres:
    image: 'postgres:14.6'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
  test:
    build:
      context: .
      dockerfile: dockerfile.test
    volumes:
      - data:/app
    working_dir: /app
    user: ${MY_USER:-root}
    depends_on:
      - mongo
      - postgres
    command: 'bash ./test.sh'
volumes:
  data:
